'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {Archive,Copy,Plus} from 'lucide-react';
import {Button} from '@/components/ui';
import {channels,getLine,products,promotions} from '@/data/mock';
import {euro} from '@/lib/utils';
import {normalizeProduct,PRODUCT_STORAGE_KEY,referencesOf} from '@/lib/catalog';
import type {Product,ProductReference,Promotion} from '@/types/promo';

export function ProductDetail({id}:{id:string}){
 const[local,setLocal]=useState<Product[]>([]),[savedPromotions,setSavedPromotions]=useState<Promotion[]>([]),[tab,setTab]=useState('overview'),[adding,setAdding]=useState(false);
 useEffect(()=>{const timer=setTimeout(()=>{setLocal((JSON.parse(localStorage.getItem(PRODUCT_STORAGE_KEY)||'[]') as Product[]).map(normalizeProduct));setSavedPromotions(JSON.parse(localStorage.getItem('promo-pulse-promotions')||'[]'))},0);return()=>clearTimeout(timer)},[]);
 const all=useMemo(()=>Array.from(new Map([...products.map(normalizeProduct),...local].map(p=>[p.id,p])).values()),[local]);
 const product=all.find(p=>p.id===id);const related=useMemo(()=>[...savedPromotions,...promotions].filter(p=>p.products.some(x=>x.productId===id)),[id,savedPromotions]);
 if(!product)return <div><h1 className="text-2xl font-bold">Produit introuvable</h1><Link className="mt-4 inline-block text-mint-700" href="/products">Retour aux produits</Link></div>;
 function persist(updated:Product){const next=[...local.filter(p=>p.id!==updated.id),updated];setLocal(next);localStorage.setItem(PRODUCT_STORAGE_KEY,JSON.stringify(next))}
 function archive(){persist({...product!,status:'Archivé',updatedAt:new Date().toISOString()})}
 function duplicate(){const stamp=new Date().getTime();const copy={...product!,id:`local-product-${stamp}`,name:`${product!.name} — copie`,status:'Actif' as const,references:referencesOf(product!).map(r=>({...r,id:`ref-${stamp}-${r.id}`}))};const next=[copy,...local];setLocal(next);localStorage.setItem(PRODUCT_STORAGE_KEY,JSON.stringify(next))}
 function promotionDraft(){localStorage.setItem('promo-pulse-draft',JSON.stringify({selectedProducts:[product!.id],selectedLineIds:[]}))}
 return <div className="space-y-7"><Link className="text-sm font-semibold text-navy-500" href="/products">← Produits</Link><header className="flex flex-col gap-4 border-b border-navy-100 pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><h1 className="text-3xl font-black">{product.name}</h1><span className="rounded-full bg-navy-50 px-2.5 py-1 text-xs font-bold text-navy-600">{product.status??'Actif'}</span></div><p className="mt-2 text-navy-500">{getLine(product.lineId)?.name} • {product.category||getLine(product.lineId)?.category}</p></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={duplicate}><Copy className="mr-2" size={15}/>Dupliquer</Button><Button variant="secondary" onClick={archive}><Archive className="mr-2" size={15}/>Archiver</Button><Link href="/promotions/new" onClick={promotionDraft}><Button>Créer une promotion</Button></Link></div></header>
 <nav className="flex gap-6 overflow-x-auto border-b" aria-label="Sections du produit">{[['overview','Vue d’ensemble'],['references','Références'],['promotions','Promotions'],['performance','Performance']].map(([key,label])=><button className={`whitespace-nowrap border-b-2 pb-3 text-sm font-bold ${tab===key?'border-mint-500 text-navy-900':'border-transparent text-navy-500'}`} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==='overview'&&<section className="grid gap-8 lg:grid-cols-2"><Section title="Informations"><Definition label="Gamme" value={getLine(product.lineId)?.name}/><Definition label="Catégorie" value={product.category||getLine(product.lineId)?.category}/><Definition label="Références" value={String(referencesOf(product).length)}/></Section><Section title="Enseignes / canaux"><p className="text-sm text-navy-600">{(product.channelIds??[]).map(cid=>channels.find(c=>c.id===cid)?.name).filter(Boolean).join(', ')||'Aucune association enregistrée. Une promotion reste possible.'}</p><Definition label="Promotions liées" value={String(related.length)}/></Section></section>}
 {tab==='references'&&<section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Références</h2><Button variant="secondary" onClick={()=>setAdding(true)}><Plus className="mr-2" size={15}/>Ajouter une référence</Button></div><div className="divide-y rounded-2xl border bg-white">{referencesOf(product).map(ref=><div className="grid gap-3 p-5 md:grid-cols-5" key={ref.id}><div className="font-bold">{ref.label}</div><Definition label="EAN" value={ref.ean||'—'}/><Definition label="Conditionnement" value={ref.packaging||'—'}/><Definition label="Prix habituel" value={ref.usualPrice!=null?euro(ref.usualPrice):'—'}/><Definition label="PRI" value={ref.unitCost!=null?euro(ref.unitCost):'—'}/></div>)}</div>{adding&&<ReferenceForm close={()=>setAdding(false)} save={(ref)=>{persist({...product,references:[...referencesOf(product),ref]});setAdding(false)}}/>}</section>}
 {tab==='promotions'&&<PromotionList items={related}/>} {tab==='performance'&&<section><h2 className="text-xl font-bold">Performance</h2>{related.some(p=>p.result)?<p className="mt-4 text-sm text-navy-600">{related.filter(p=>p.result).length} opération(s) terminée(s) avec des résultats renseignés.</p>:<p className="mt-4 text-sm text-navy-600">Aucune donnée de performance réelle disponible.</p>}</section>}</div>
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-4 text-xl font-bold">{title}</h2><div className="space-y-4 border-l-2 border-navy-100 pl-5">{children}</div></section>}
function Definition({label,value}:{label:string;value?:string}){return <div><span className="block text-xs font-semibold uppercase tracking-wide text-navy-400">{label}</span><span className="mt-1 block text-sm font-semibold">{value||'—'}</span></div>}
function PromotionList({items}:{items:Promotion[]}){return <section><h2 className="text-xl font-bold">Promotions du produit</h2>{items.length?<div className="mt-4 divide-y rounded-2xl border bg-white">{items.map(p=><Link className="flex justify-between p-4 hover:bg-navy-50" href={`/promotions/${p.id}`} key={p.id}><span className="font-semibold">{p.name}</span><span className="text-sm text-navy-500">{p.operationalStatus}</span></Link>)}</div>:<p className="mt-4 text-sm text-navy-600">Aucune promotion associée.</p>}</section>}
function ReferenceForm({close,save}:{close:()=>void;save:(r:ProductReference)=>void}){const[label,setLabel]=useState(''),[ean,setEan]=useState(''),[price,setPrice]=useState(''),[cost,setCost]=useState('');return <div className="fixed inset-0 z-50 flex justify-end bg-navy-950/25" onClick={close}><form className="h-full w-full max-w-md bg-white p-6" onSubmit={e=>{e.preventDefault();save({id:`ref-${Date.now()}`,label:label||'Référence',ean:ean||undefined,usualPrice:price?Number(price.replace(',','.')):undefined,unitCost:cost?Number(cost.replace(',','.')):undefined,status:'Actif'})}} onClick={e=>e.stopPropagation()}><h2 className="text-xl font-bold">Ajouter une référence</h2>{[['Libellé',label,setLabel],['EAN',ean,setEan],['Prix habituel',price,setPrice],['PRI / coût',cost,setCost]].map(([l,v,set])=><label className="mt-4 block text-sm font-semibold" key={l as string}>{l as string}<input className="mt-2 w-full rounded-xl border p-3" value={v as string} onChange={e=>(set as (v:string)=>void)(e.target.value)}/></label>)}<div className="mt-6 flex gap-2"><Button type="button" variant="secondary" onClick={close}>Annuler</Button><Button type="submit">Ajouter</Button></div></form></div>}
