'use client';

import { useState } from 'react';
import { Check, CircleHelp, Info, SlidersHorizontal, X } from 'lucide-react';
import { Button } from '@/components/ui';
import { cn } from '@/lib/utils';
import { calculateEquivalentBenefit, calculatePackBenefit, defaultMechanicConfiguration, promotionMechanics, type MechanicConfiguration, type MechanicId, type MechanicObjective, type PromotionMechanic } from '@/lib/promotion-engine/mechanics';
import { mechanicObjectives, objectiveGuidance, recommendMechanics } from '@/lib/promotion-engine/mechanic-recommendations';
import { assessMechanicCompliance } from '@/lib/compliance-engine';
import type { ChannelType } from '@/types/promo';

export function MechanicSelector({ channel, category, selectedId, configuration, onChange }: { channel?: ChannelType; category?: string; selectedId: MechanicId | ''; configuration: MechanicConfiguration; onChange: (id: MechanicId, configuration: MechanicConfiguration) => void }) {
  const [infoId, setInfoId] = useState<MechanicId | null>(null);
  const [customId, setCustomId] = useState<MechanicId | null>(null);
  const [helpOpen, setHelpOpen] = useState(false);
  const [objectives, setObjectives] = useState<MechanicObjective[]>([]);
  const [highlightedId, setHighlightedId] = useState<MechanicId | null>(null);
  const available = promotionMechanics.filter((mechanic) => !channel || mechanic.applicableChannels.includes(channel));
  const recommendations = recommendMechanics({ objectives, channel, category });
  const compliance = selectedId ? assessMechanicCompliance({ category, mechanicId:selectedId, equivalentBenefits:[calculateEquivalentBenefit(selectedId, configuration)] }) : null;

  const choose = (mechanic: PromotionMechanic, patch: Partial<MechanicConfiguration> = {}) => onChange(mechanic.id, { ...configuration, ...patch });
  const customize = (mechanic: PromotionMechanic) => { choose(mechanic); setCustomId(customId === mechanic.id ? null : mechanic.id); };
  const toggleObjective = (objective: MechanicObjective) => setObjectives((current) => current.includes(objective) ? current.filter((item) => item !== objective) : current.length < 2 ? [...current, objective] : current);
  const showMechanic = (id: MechanicId) => {
    setHelpOpen(false); setHighlightedId(id);
    window.setTimeout(() => document.getElementById(`mechanic-${id}`)?.scrollIntoView({ behavior:'smooth', block:'center' }), 50);
    window.setTimeout(() => setHighlightedId(null), 1800);
  };

  return <section>
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><h2 className="text-2xl font-bold">Choisissez votre mécanique promotionnelle</h2><p className="mt-2 text-navy-500">Sélectionnez une mécanique ou laissez Promo Pulse vous guider selon votre objectif.</p><p className="mt-2 text-sm text-navy-400">Vous savez déjà laquelle utiliser ? Sélectionnez-la directement.</p></div><Button className="shrink-0" variant="ghost" onClick={() => setHelpOpen(true)}><CircleHelp className="mr-2" size={17} />M’aider à choisir</Button></div>

    <div className="mechanic-list mt-7 divide-y divide-navy-100 border-y border-navy-100">
      {available.map((mechanic) => {
        const selected = selectedId === mechanic.id;
        const equivalent = calculateEquivalentBenefit(mechanic.id, configuration);
        return <article id={`mechanic-${mechanic.id}`} key={mechanic.id} className={cn('mechanic-row relative py-5 transition', selected && 'is-selected', highlightedId === mechanic.id && 'is-highlighted')} onMouseEnter={() => setInfoId(mechanic.id)} onMouseLeave={() => setInfoId(null)} onFocus={() => setInfoId(mechanic.id)} onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setInfoId(null); }}>
          <div className="grid gap-4 lg:grid-cols-[minmax(210px,.8fr)_minmax(0,1.6fr)] lg:items-start">
            <div className="flex items-start gap-3"><button aria-label={`${selected ? 'Mécanique sélectionnée' : 'Choisir'} : ${mechanic.name}`} className={cn('mechanic-select mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border transition', selected ? 'border-mint-500 bg-mint-500 text-navy-900' : 'border-navy-200 hover:border-mint-500')} onClick={() => choose(mechanic)} type="button">{selected && <Check size={14}/>}</button><div><div className="flex items-center gap-2"><h3 className="font-bold text-navy-900">{mechanic.name}</h3><button aria-expanded={infoId === mechanic.id} aria-label={`Informations sur ${mechanic.name}`} className="rounded p-1 text-navy-400 hover:bg-navy-50 hover:text-navy-700 focus:outline-none focus:ring-2 focus:ring-mint-300" onClick={() => setInfoId(infoId === mechanic.id ? null : mechanic.id)} type="button"><Info size={14}/></button></div>{mechanic.subtitle && <p className="mt-0.5 text-xs font-semibold uppercase tracking-wider text-navy-400" title="Conditionnement promotionnel créé spécifiquement en regroupant plusieurs unités dans un même pack.">{mechanic.subtitle}</p>}<p className="mt-1 text-sm leading-5 text-navy-500">{mechanic.description}</p></div></div>
            <div><div className="flex flex-wrap gap-2">{mechanic.id === 'multi-buy' ? <Preset active={selected && configuration.boughtQuantity === 2 && configuration.freeQuantity === 1} label="2+1 offert" onClick={() => choose(mechanic,{boughtQuantity:2,freeQuantity:1})}/> : mechanic.presets.map((preset) => <Preset key={preset} active={selected && configuration.value === preset} label={presetLabel(mechanic.id,preset)} onClick={() => choose(mechanic,{value:preset})}/>) }<button className="rounded-lg px-3 py-2 text-sm font-semibold text-navy-500 underline-offset-4 transition hover:bg-navy-50 hover:text-navy-900 hover:underline focus:outline-none focus:ring-2 focus:ring-mint-300" onClick={() => customize(mechanic)} type="button"><SlidersHorizontal className="mr-1.5 inline" size={14}/>Personnaliser</button></div>{selected && ['second-product','multi-buy','promo-pack'].includes(mechanic.id) && <p className="mt-3 text-sm font-semibold tabular-nums text-mint-700">Avantage équivalent : {formatPercent(equivalent)}</p>}{customId === mechanic.id && <Customization mechanic={mechanic} configuration={configuration} onChange={(patch) => choose(mechanic,patch)} />}</div>
          </div>
          {infoId === mechanic.id && <MechanicPopover mechanic={mechanic} equivalent={equivalent}/>} 
        </article>;
      })}
    </div>
    {compliance && <div className="mt-5 flex items-start gap-2 rounded-lg bg-blue-50 px-4 py-3 text-sm text-blue-800"><Info className="mt-0.5 shrink-0" size={16}/><p><strong>Vérification réglementaire incomplète.</strong> {compliance.explanation} Avantage cumulé actuellement structuré : {formatPercent(compliance.cumulativeBenefit)}.</p></div>}

    {helpOpen && <div className="fixed inset-0 z-50 flex justify-end bg-navy-950/20" onClick={() => setHelpOpen(false)} role="presentation"><aside aria-label="Aide au choix de la mécanique" className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-mint-600">Aide facultative</p><h2 className="mt-2 text-2xl font-bold">Quel est votre objectif ?</h2><p className="mt-1 text-sm text-navy-500">Sélectionnez jusqu’à 2 priorités.</p></div><button aria-label="Fermer" className="rounded-lg p-2 hover:bg-navy-50 focus:outline-none focus:ring-2 focus:ring-mint-300" onClick={() => setHelpOpen(false)} type="button"><X size={19}/></button></div><div className="mt-6 flex flex-wrap gap-2">{mechanicObjectives.map((objective) => <button aria-pressed={objectives.includes(objective.id)} className={cn('rounded-xl border px-3 py-2 text-left text-sm font-semibold transition', objectives.includes(objective.id) ? 'border-mint-500 bg-mint-50' : 'border-navy-100 hover:border-navy-200 hover:bg-navy-50', objectives.length === 2 && !objectives.includes(objective.id) && 'cursor-not-allowed opacity-45')} disabled={objectives.length === 2 && !objectives.includes(objective.id)} key={objective.id} onClick={() => toggleObjective(objective.id)} type="button">{objective.label}</button>)}</div>{objectives.length > 0 && <div className="mt-7"><h3 className="text-lg font-bold">Mécaniques à considérer</h3><p className="mt-2 text-sm leading-6 text-navy-500">{objectiveGuidance[objectives[0]]?.message}</p><div className="mt-5 divide-y divide-navy-100 border-y border-navy-100">{recommendations.map((mechanic,index) => <div className="py-4" key={mechanic.id}><p className="text-xs font-bold uppercase tracking-wider text-navy-400">{index+1} — À considérer</p><h4 className="mt-1 font-bold">{mechanic.name}</h4><p className="mt-1 text-sm text-navy-500">{mechanic.strengths.slice(0,2).join(' · ')}</p><p className="mt-2 text-xs text-orange-700"><strong>À surveiller :</strong> {mechanic.watchouts[0]}</p><button className="mt-3 text-sm font-semibold text-mint-700 hover:underline focus:outline-none focus:ring-2 focus:ring-mint-300" onClick={() => showMechanic(mechanic.id)} type="button">Voir cette mécanique</button></div>)}</div><p className="mt-4 rounded-lg bg-navy-50 p-3 text-xs leading-5 text-navy-600">{objectiveGuidance[objectives[0]]?.watchout}</p></div>}<p className="mt-7 text-xs leading-5 text-navy-400">Orientations V1 fondées sur des heuristiques générales. Vos performances historiques réelles auront priorité lorsqu’un volume de données suffisant sera disponible.</p></aside></div>}
  </section>;
}

function Preset({active,label,onClick}:{active:boolean;label:string;onClick:()=>void}) { return <button aria-pressed={active} className={cn('mechanic-preset rounded-lg border px-3 py-2 text-sm font-semibold tabular-nums transition', active ? 'border-navy-900 bg-navy-900 text-white' : 'border-navy-100 bg-white text-navy-700 hover:-translate-y-px hover:border-mint-400 hover:bg-mint-50')} onClick={onClick} type="button">{label}</button>; }
function presetLabel(id:MechanicId,value:number) { if(id==='second-product') return `2e à -${value} %`; if(id==='extra-quantity') return `+${value} %`; if(id==='loyalty-credit') return `${value} %`; return `-${value} %`; }
function formatPercent(value:number) { return `${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(value)} %`; }

function Customization({mechanic,configuration,onChange}:{mechanic:PromotionMechanic;configuration:MechanicConfiguration;onChange:(patch:Partial<MechanicConfiguration>)=>void}) {
  return <div className="mt-4 grid gap-3 rounded-xl bg-navy-50 p-4 sm:grid-cols-2">{['immediate-discount','second-product','extra-quantity','loyalty-credit'].includes(mechanic.id) && <MiniNumber label={mechanic.id==='extra-quantity'?'Quantité offerte':'Valeur personnalisée'} unit="%" value={configuration.value} onChange={(value)=>onChange({value})}/>} {mechanic.id==='multi-buy' && <><MiniNumber label="Quantité achetée" unit="unités" value={configuration.boughtQuantity} onChange={(value)=>onChange({boughtQuantity:value})}/><MiniNumber label="Quantité offerte" unit="unités" value={configuration.freeQuantity} onChange={(value)=>onChange({freeQuantity:value})}/></>}{mechanic.id==='promo-pack' && <><MiniNumber label="Nombre d’unités dans le pack" unit="unités" value={configuration.packUnits} onChange={(value)=>onChange({packUnits:value})}/><MiniNumber label="Quantité supplémentaire offerte" unit="unités" value={configuration.packExtraQuantity} onChange={(value)=>onChange({packExtraQuantity:value})}/><MiniNumber label="Prix habituel cumulé" unit="€" value={configuration.packRegularPrice} onChange={(value)=>onChange({packRegularPrice:value})}/><MiniNumber label="Prix du pack" unit="€" value={configuration.packPrice} onChange={(value)=>onChange({packPrice:value})}/><p className="text-sm font-semibold sm:col-span-2">Économie consommateur : {(configuration.packRegularPrice-configuration.packPrice).toLocaleString('fr-FR',{maximumFractionDigits:2})} € · {formatPercent(calculatePackBenefit(configuration.packRegularPrice,configuration.packPrice))}</p></>}{mechanic.id==='coupon-refund' && <><label className="text-sm font-semibold">Type<select className="mt-2 w-full rounded-lg border border-navy-100 bg-white px-3 py-2" value={configuration.couponType} onChange={(event)=>onChange({couponType:event.target.value as MechanicConfiguration['couponType']})}><option>BRI / coupon immédiat</option><option>Bon de réduction différé</option><option>ODR / remboursement</option></select></label><label className="text-sm font-semibold">Unité<select className="mt-2 w-full rounded-lg border border-navy-100 bg-white px-3 py-2" value={configuration.couponUnit} onChange={(event)=>onChange({couponUnit:event.target.value as '€'|'%'})}><option>€</option><option>%</option></select></label><MiniNumber label="Valeur" unit={configuration.couponUnit} value={configuration.value} onChange={(value)=>onChange({value})}/></>}</div>;
}
function MiniNumber({label,unit,value,onChange}:{label:string;unit:string;value:number;onChange:(value:number)=>void}) { return <label className="text-sm font-semibold">{label}<span className="mt-2 flex items-center rounded-lg border border-navy-100 bg-white focus-within:border-mint-500 focus-within:ring-2 focus-within:ring-mint-100"><input className="min-w-0 flex-1 bg-transparent px-3 py-2 outline-none" min="0" type="number" value={value} onFocus={(event)=>event.currentTarget.select()} onChange={(event)=>onChange(Number(event.target.value))}/><span className="border-l border-navy-100 px-2 text-xs text-navy-400">{unit}</span></span></label>; }

function MechanicPopover({mechanic,equivalent}:{mechanic:PromotionMechanic;equivalent:number}) {
  const profileEntries=Object.entries(mechanic.profile).slice(0,5);
  return <div className="mechanic-popover absolute right-0 top-16 z-30 w-[min(340px,calc(100vw-3rem))] rounded-xl border border-navy-100 bg-white p-4 shadow-xl" role="tooltip"><h4 className="font-bold">{mechanic.name}</h4><div className="mt-3 grid gap-3 text-xs"><div><p className="font-bold text-green-800">Particulièrement adaptée à</p><ul className="mt-1 space-y-1 text-navy-600">{mechanic.strengths.slice(0,3).map((item)=><li key={item}>• {item}</li>)}</ul></div><div><p className="font-bold text-orange-800">À surveiller</p><ul className="mt-1 space-y-1 text-navy-600">{mechanic.watchouts.slice(0,2).map((item)=><li key={item}>• {item}</li>)}</ul></div></div><p className="mt-3 text-[10px] font-bold uppercase tracking-wider text-navy-400">Profil indicatif</p><div className="mt-2 space-y-1">{profileEntries.map(([key,value])=><div className="flex items-center justify-between gap-3 text-xs" key={key}><span>{profileLabel(key)}</span><span aria-label={`${profileLabel(key)} : ${value} sur 5`} className="tracking-[2px] text-mint-600">{'●'.repeat(value)}<span className="text-navy-100">{'●'.repeat(5-value)}</span></span></div>)}</div>{['second-product','multi-buy'].includes(mechanic.id) && <p className="mt-3 border-t border-navy-100 pt-3 text-xs font-bold text-mint-700">Avantage équivalent : {formatPercent(equivalent)}</p>}</div>;
}
function profileLabel(key:string){return ({revenue:'CA',volume:'Volume',acquisition:'Recrutement',discovery:'Découverte',loyalty:'Fidélisation',marginProtection:'Marge',visibility:'Visibilité',priceFace:'Prix facial'} as Record<string,string>)[key]??key;}

export { defaultMechanicConfiguration };
