'use client';

import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,Copy,Ellipsis,FileText,Pencil,RefreshCw,X} from 'lucide-react';
import {Button,StatusBadge,Tabs} from '@/components/ui';
import {getChannel,getLine,getProduct,promotions} from '@/data/mock';
import {euro,shortDate} from '@/lib/utils';
import type {Product,Promotion,PromotionResult} from '@/types/promo';

const savedKey='promo-pulse-promotions',draftKey='promo-pulse-draft',localProductsKey='promo-pulse-products';
const tabs=['Vue d’ensemble','Analyse','Réglementation','Résultats','Historique'];
const documentTypes=['Fiche interne','Document enseigne','Préparation négociation','Analyse'];

export function PromotionDetail({id}:{id:string}){
 const router=useRouter();const[active,setActive]=useState(tabs[0]);const[local,setLocal]=useState<Promotion|null>(null);const[savedPromotions,setSavedPromotions]=useState<Promotion[]>([]);const[loaded,setLoaded]=useState(false);const[localProducts,setLocalProducts]=useState<Product[]>([]);const[documentModal,setDocumentModal]=useState(false);const[documentType,setDocumentType]=useState(documentTypes[0]);const[feedback,setFeedback]=useState('');const[menu,setMenu]=useState(false);const[resultForm,setResultForm]=useState({actualVolume:0,actualRevenue:0,actualExpenses:0});
 useEffect(()=>{const timer=setTimeout(()=>{const saved=JSON.parse(localStorage.getItem(savedKey)||'[]') as Promotion[];setLocal(saved.find((p)=>p.id===id)??null);setSavedPromotions(saved);setLocalProducts(JSON.parse(localStorage.getItem(localProductsKey)||'[]'));setFeedback(localStorage.getItem('promo-pulse-feedback')||'');localStorage.removeItem('promo-pulse-feedback');setLoaded(true)},0);return()=>clearTimeout(timer)},[id]);
 const promotion=local??promotions.find((p)=>p.id===id);
 const allPromotions=[...savedPromotions,...promotions];
 if(!promotion&&!loaded)return <p className="text-sm text-navy-500">Chargement de la promotion…</p>;
 if(!promotion)return <div><h1 className="text-xl font-bold">Promotion introuvable</h1><Link className="mt-4 inline-block font-semibold text-mint-600" href="/promotions">Retour aux promotions</Link></div>;
 const currentPromotion:Promotion=promotion;
 const channelNames=currentPromotion.channelIds.map((channelId)=>getChannel(channelId)?.name).filter(Boolean).join(', ');
 const selectedProducts=currentPromotion.products.map((item)=>getProduct(item.productId)??localProducts.find((p)=>p.id===item.productId)).filter(Boolean) as Product[];
 const productNames=selectedProducts.map((p)=>p.name).join(', '),volume=currentPromotion.products.reduce((sum,item)=>sum+item.forecastVolume,0),expenses=currentPromotion.expenses.reduce((sum,item)=>sum+item.amount,0);
 const economics=currentPromotion.economics??{inputVolume:volume,inputUnit:'unités' as const,distributedUnits:volume,soldUnits:volume,offeredUnits:0,transactionCount:volume,remainderUnits:0,averageSellingPrice:currentPromotion.promoPrice,productCost:(currentPromotion.costPrice??0)*volume,expenses,marginTarget:currentPromotion.minimumMarginRate??15,consumerBenefit:currentPromotion.discountRate,roiValidated:false};
 const similar=allPromotions.filter((item)=>item.id!==currentPromotion.id&&(item.productLineId===currentPromotion.productLineId||item.channelIds.some((channel)=>currentPromotion.channelIds.includes(channel))||item.mechanicId===currentPromotion.mechanicId)).slice(0,4);
 function seedDraft(mode:'edit'|'duplicate'|'reuse') {const isReuse=mode==='reuse';localStorage.setItem(draftKey,JSON.stringify({editingPromotionId:mode==='edit'?currentPromotion.id:undefined,selectedProducts:currentPromotion.products.map((p)=>p.productId),selectedLineIds:[],channelIds:currentPromotion.channelIds,startDate:isReuse?'':currentPromotion.startDate,endDate:isReuse?'':currentPromotion.endDate,mechanic:currentPromotion.mechanic,mechanicId:currentPromotion.mechanicId,mechanicConfiguration:currentPromotion.mechanicConfiguration,volumeMode:'global',globalVolume:economics.inputVolume,referenceVolumes:Object.fromEntries(currentPromotion.products.map((p)=>[p.productId,p.forecastVolume])),economicsMode:'global',referenceEconomics:{},usualPrice:currentPromotion.usualPrice,promoPrice:currentPromotion.promoPrice,costPrice:currentPromotion.costPrice??0,promotionalUnitCost:0,baseQuantity:200,quantityUnit:'g',expenses,expenseMode:currentPromotion.expenses.length>1?'detailed':'global',expenseDetails:Object.fromEntries(currentPromotion.expenses.map((e)=>[e.label,e.amount])),customExpenses:[],minimumMarginRate:currentPromotion.minimumMarginRate??15,name:mode==='edit'?currentPromotion.name:`${currentPromotion.name} — ${mode==='duplicate'?'copie':'nouvelle opération'}`}));router.push('/promotions/new')}
 function duplicate(){const saved=JSON.parse(localStorage.getItem(savedKey)||'[]') as Promotion[];const copy={...currentPromotion,id:`local-${Date.now()}`,name:`${currentPromotion.name} — copie`,operationalStatus:'Brouillon' as const,result:undefined,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};localStorage.setItem(savedKey,JSON.stringify([copy,...saved]));localStorage.setItem('promo-pulse-feedback','Brouillon dupliqué');router.push(`/promotions/${copy.id}`)}
 function saveResults(){const unitCost=currentPromotion.costPrice??0;const actualMargin=resultForm.actualRevenue-resultForm.actualVolume*unitCost-resultForm.actualExpenses;const result:PromotionResult={...resultForm,actualMargin,actualRoi:0};const updated={...currentPromotion,result,updatedAt:new Date().toISOString()};const saved=JSON.parse(localStorage.getItem(savedKey)||'[]') as Promotion[];localStorage.setItem(savedKey,JSON.stringify([updated,...saved.filter((p)=>p.id!==currentPromotion.id)]));setLocal(updated);setFeedback('Résultats enregistrés')}
 function archive(){const saved=JSON.parse(localStorage.getItem(savedKey)||'[]') as Promotion[];const updated={...currentPromotion,operationalStatus:'Archivée' as const};localStorage.setItem(savedKey,JSON.stringify([updated,...saved.filter((p)=>p.id!==currentPromotion.id)]));setLocal(updated);setMenu(false)}
 return <div className="mx-auto max-w-7xl space-y-6">
  <nav className="flex items-center gap-2 text-sm text-navy-500"><Link className="inline-flex items-center gap-2 font-semibold hover:text-navy-900" href="/promotions"><ArrowLeft size={15}/>Promotions</Link><span>/</span><span className="truncate">{currentPromotion.name}</span></nav>
  {feedback&&<div role="status" className="border-l-2 border-mint-500 bg-mint-50 px-4 py-3 text-sm font-semibold">{feedback}</div>}
  <header className="border-b border-navy-100 pb-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><h1 className="text-3xl font-black tracking-tight">{currentPromotion.name}</h1><p className="mt-2 text-navy-500">{channelNames} · {getLine(currentPromotion.productLineId).name} · {shortDate(currentPromotion.startDate)} → {shortDate(currentPromotion.endDate)}</p><div className="mt-4 flex flex-wrap gap-5 text-sm"><LabeledStatus label="Statut opérationnel" status={currentPromotion.operationalStatus}/><LabeledStatus label="État de contrôle" status={currentPromotion.controlStatus}/></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>seedDraft('edit')}><Pencil className="mr-2" size={15}/>Modifier</Button><Button variant="secondary" onClick={duplicate}><Copy className="mr-2" size={15}/>Dupliquer</Button><Button variant="secondary" onClick={()=>seedDraft('reuse')}><RefreshCw className="mr-2" size={15}/>Réutiliser</Button><Button onClick={()=>setDocumentModal(true)}><FileText className="mr-2" size={15}/>Générer un document</Button><div className="relative"><Button aria-label="Actions supplémentaires" variant="ghost" onClick={()=>setMenu(!menu)}><Ellipsis size={18}/></Button>{menu&&<div className="absolute right-0 z-10 mt-2 w-40 rounded-xl border border-navy-100 bg-white p-1 shadow-lg"><button className="w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-navy-50" onClick={archive}>Archiver</button></div>}</div></div></div></header>
  <Tabs active={active} items={tabs} onSelect={setActive}/>
  {active==='Vue d’ensemble'&&<Overview promotion={currentPromotion} economics={economics} channelNames={channelNames} productNames={productNames||getLine(currentPromotion.productLineId).name}/>}
  {active==='Analyse'&&<Analysis promotion={currentPromotion}/>}
  {active==='Réglementation'&&<Regulations promotion={currentPromotion}/>}
  {active==='Résultats'&&<Results promotion={currentPromotion} form={resultForm} setForm={setResultForm} save={saveResults}/>}
  {active==='Historique'&&<History items={similar}/>}
  {documentModal&&<DocumentDialog promotion={currentPromotion} type={documentType} setType={setDocumentType} close={()=>setDocumentModal(false)}/>}
 </div>
}

function Overview({promotion,economics,channelNames,productNames}:{promotion:Promotion;economics:NonNullable<Promotion['economics']>;channelNames:string;productNames:string}){const gap=promotion.marginRate-economics.marginTarget;return <div className="space-y-8"><Section title="Opération"><dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><Item label="Enseigne / canal" value={channelNames}/><Item label="Période" value={`${shortDate(promotion.startDate)} → ${shortDate(promotion.endDate)}`}/><Item label="Mécanique" value={promotion.mechanic}/><Item label="Produits" value={productNames}/></dl><details className="mt-4 text-sm"><summary className="cursor-pointer font-semibold">Voir le détail de la mécanique</summary><p className="mt-2 text-navy-500">Avantage consommateur : {economics.consumerBenefit.toFixed(1)} % · Prix moyen : {euro(economics.averageSellingPrice)}</p></details></Section><Section title="Économie prévisionnelle"><dl className="grid grid-cols-2 gap-6 lg:grid-cols-5"><Metric label="CA prévisionnel" value={euro(promotion.forecastRevenue)}/><Metric label="Marge prévisionnelle" value={euro(promotion.forecastMargin)}/><Metric label="Taux de marge" value={`${promotion.marginRate.toFixed(1)} %`}/><Metric label="Objectif" value={`${economics.marginTarget.toFixed(1)} %`}/><Metric label="Dépenses" value={euro(economics.expenses)}/></dl><p className={`mt-4 text-sm font-bold ${gap<0?'text-orange-700':'text-green-700'}`}>{gap<0?`${Math.abs(gap).toFixed(1)} pts sous votre objectif`:`+${gap.toFixed(1)} pts au-dessus de votre objectif`}</p></Section><Section title="Volume"><p className="text-2xl font-black tabular-nums">{economics.inputVolume.toLocaleString('fr-FR')} {economics.inputUnit}</p><p className="mt-2 text-sm text-navy-500">{economics.distributedUnits.toLocaleString('fr-FR')} unités au total · {economics.soldUnits.toLocaleString('fr-FR')} vendues · {economics.offeredUnits.toLocaleString('fr-FR')} offertes</p>{economics.promotionalFormat&&<p className="mt-1 text-sm">{economics.promotionalFormat} par format</p>}</Section><Section title="Contrôles"><div className="flex flex-wrap gap-6"><LabeledStatus label="Réglementation" status={promotion.controlStatus}/><LabeledStatus label="Rentabilité" status={promotion.marginRate<(promotion.minimumMarginRate??15)?'Vigilance':'Conforme'}/></div></Section></div>}
function Analysis({promotion}:{promotion:Promotion}){const below=promotion.marginRate<(promotion.minimumMarginRate??15);return <div className="space-y-8"><Section title="Rentabilité"><p className="text-3xl font-black">{promotion.marginRate.toFixed(1)} %</p><p className="mt-2 text-sm text-navy-500">{below?'Objectif de marge non atteint.':'Objectif de marge atteint.'}</p></Section><Section title="Points de vigilance">{below?<p className="border-l-2 border-orange-400 pl-3">Marge sous objectif.</p>:<p className="text-navy-500">Aucun point de vigilance économique.</p>}</Section><Section title="Optimisations">{promotion.scenarios.length?<div className="divide-y divide-navy-100">{promotion.scenarios.map((scenario)=><div className="py-3" key={scenario.name}><strong>{scenario.name}</strong><p className="mt-1 text-sm text-navy-500">Marge {scenario.marginRate.toFixed(1)} % · Remise {scenario.discountRate.toFixed(1)} %</p></div>)}</div>:<p className="text-navy-500">Aucun scénario enregistré.</p>}</Section></div>}
function Regulations({promotion}:{promotion:Promotion}){return <Section title="Contrôles réglementaires"><p className="mb-5 text-sm text-navy-500">Les contrôles du prototype ne constituent pas un avis juridique.</p><div className="divide-y divide-navy-100">{promotion.checks.map((check)=><details className="py-4" key={check.id}><summary className="flex cursor-pointer items-center justify-between gap-4"><strong>{check.label}</strong><StatusBadge status={check.status}/></summary><div className="mt-3 space-y-2 text-sm text-navy-500"><p>{check.explanation}</p><p>Données utilisées : mécanique, période et volume disponibles.</p>{check.source&&<p>Source : {check.source} · {check.version}</p>}</div></details>)}</div></Section>}
function Results({promotion,form,setForm,save}:{promotion:Promotion;form:{actualVolume:number;actualRevenue:number;actualExpenses:number};setForm:(v:{actualVolume:number;actualRevenue:number;actualExpenses:number})=>void;save:()=>void}){if(promotion.result)return <Section title="Prévision vs réel"><table className="w-full text-sm"><thead><tr className="border-b"><th className="py-3 text-left">Indicateur</th><th>Prévu</th><th>Réel</th></tr></thead><tbody><Compare label="Volume" planned={promotion.economics?.distributedUnits??promotion.products.reduce((s,p)=>s+p.forecastVolume,0)} actual={promotion.result.actualVolume}/><Compare label="CA" planned={promotion.forecastRevenue} actual={promotion.result.actualRevenue} money/><Compare label="Marge" planned={promotion.forecastMargin} actual={promotion.result.actualMargin} money/></tbody></table></Section>;if(promotion.operationalStatus!=='Terminée')return <Section title="Résultats"><p className="font-semibold">Les résultats pourront être renseignés à la fin de l’opération.</p></Section>;return <Section title="Saisir les résultats"><div className="grid gap-4 sm:grid-cols-3"><NumberField label="Volume réel" value={form.actualVolume} onChange={(actualVolume)=>setForm({...form,actualVolume})}/><NumberField label="CA réel" value={form.actualRevenue} onChange={(actualRevenue)=>setForm({...form,actualRevenue})}/><NumberField label="Dépenses réelles" value={form.actualExpenses} onChange={(actualExpenses)=>setForm({...form,actualExpenses})}/></div><Button className="mt-5" onClick={save}>Enregistrer les résultats</Button></Section>}
function History({items}:{items:Promotion[]}){return <Section title="Opérations similaires">{items.length?<div className="divide-y divide-navy-100">{items.map((item)=><Link className="flex items-center justify-between py-4 hover:text-mint-700" href={`/promotions/${item.id}`} key={item.id}><span><strong>{item.name}</strong><span className="mt-1 block text-sm text-navy-500">{shortDate(item.startDate)} → {shortDate(item.endDate)} · {item.mechanic}</span></span><span>Voir</span></Link>)}</div>:<p className="text-navy-500">Aucune opération similaire pour le moment.</p>}</Section>}
function DocumentDialog({promotion,type,setType,close}:{promotion:Promotion;type:string;setType:(v:string)=>void;close:()=>void}){const external=type==='Document enseigne';return <div className="fixed inset-0 z-50 flex items-center justify-center bg-navy-950/30 p-4" onClick={close}><div aria-modal="true" role="dialog" className="w-full max-w-3xl rounded-2xl bg-white p-6 shadow-2xl" onClick={(e)=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-xl font-bold">Générer un document</h2><p className="mt-1 text-sm text-navy-500">Aperçu du prototype — aucun PDF n’est encore généré.</p></div><button aria-label="Fermer" onClick={close}><X size={19}/></button></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{documentTypes.map((item)=><button className={`rounded-xl border p-3 text-left font-semibold ${type===item?'border-mint-500 bg-mint-50':'border-navy-100'}`} onClick={()=>setType(item)} key={item}>{item}</button>)}</div><div className="mt-5 bg-navy-50 p-5"><p className="text-xs font-bold uppercase text-navy-400">Aperçu · {type}</p><h3 className="mt-3 text-xl font-black">{promotion.name}</h3><p className="mt-3 text-sm">CA prévisionnel : {euro(promotion.forecastRevenue)}</p>{!external&&<><p className="mt-1 text-sm">Marge interne : {euro(promotion.forecastMargin)}</p><p className="mt-1 text-sm">PRI : {euro(promotion.costPrice??0)}</p></>}{external&&<p className="mt-3 text-sm text-blue-700">Les coûts, le PRI et la marge interne sont exclus de ce document.</p>}</div><div className="mt-5 flex justify-end"><Button disabled>Génération PDF — prochaine phase</Button></div></div></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="border-t border-navy-100 pt-5"><h2 className="text-lg font-bold">{title}</h2><div className="mt-4">{children}</div></section>}
function Metric({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold text-navy-500">{label}</dt><dd className="mt-1 text-2xl font-black tabular-nums">{value}</dd></div>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-semibold uppercase tracking-wider text-navy-400">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>}
function LabeledStatus({label,status}:{label:string;status:Promotion['operationalStatus']|Promotion['controlStatus']}){return <div><span className="mr-2 text-navy-500">{label}</span><StatusBadge status={status}/></div>}
function Compare({label,planned,actual,money}:{label:string;planned:number;actual:number;money?:boolean}){return <tr className="border-b"><th className="py-3 text-left">{label}</th><td className="text-center tabular-nums">{money?euro(planned):planned.toLocaleString('fr-FR')}</td><td className="text-center tabular-nums">{money?euro(actual):actual.toLocaleString('fr-FR')}</td></tr>}
function NumberField({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="text-sm font-semibold">{label}<input className="mt-2 w-full rounded-xl border border-navy-100 px-3 py-2.5" inputMode="decimal" placeholder="0" value={value||''} onChange={(e)=>onChange(Number(e.target.value.replace(',','.'))||0)}/></label>}
