import Link from 'next/link'; import { cn } from '@/lib/utils'; import type { ControlStatus, OperationalStatus } from '@/types/promo';
export function Button({className,variant='primary',...p}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'}){return <button className={cn('rounded-xl px-4 py-2 text-sm font-semibold transition',variant==='primary'&&'bg-mint-500 text-navy-900 hover:bg-mint-600',variant==='secondary'&&'border border-navy-100 bg-white text-navy-900 hover:border-mint-300',variant==='ghost'&&'text-navy-500 hover:bg-navy-50',className)} {...p}/>}
export function Card({className,...p}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn('rounded-2xl border border-navy-100 bg-white p-5 shadow-soft',className)} {...p}/>}
export function Badge({children,tone='info'}:{children:React.ReactNode;tone?:'success'|'warning'|'danger'|'info'|'neutral'}){return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold',tone==='success'&&'bg-green-50 text-green-700',tone==='warning'&&'bg-orange-50 text-orange-700',tone==='danger'&&'bg-red-50 text-red-700',tone==='info'&&'bg-blue-50 text-blue-700',tone==='neutral'&&'bg-navy-50 text-navy-500')}>{children}</span>}
export function StatusBadge({status}:{status:ControlStatus|OperationalStatus}){const tone=status==='Conforme'?'success':status==='Vigilance'?'warning':status==='Problème'?'danger':status==='Non vérifié'?'neutral':'info';return <Badge tone={tone}>{status}</Badge>}
export function KpiCard({label,value,emoji,caption}:{label:string;value:string|number;emoji:string;caption?:string}){return <Card><div className='flex items-start justify-between'><div><p className='text-sm text-navy-500'>{label}</p><p className='mt-2 text-3xl font-bold'>{value}</p>{caption&&<p className='mt-2 text-xs text-navy-500'>{caption}</p>}</div><span className='text-2xl'>{emoji}</span></div></Card>}
export function EmptyState({title,action}:{title:string;action:string}){return <Card className='text-center'><p className='text-lg font-semibold'>{title}</p><Button className='mt-4'>{action}</Button></Card>}
export function NavLink({href,label,active}:{href:string;label:string;active?:boolean}){return <Link className={cn('block rounded-xl px-3 py-2 text-sm font-medium',active?'bg-mint-100 text-navy-900':'text-navy-100 hover:bg-navy-700')} href={href}>{label}</Link>}
export function Tabs({items,active}:{items:string[];active:string}){return <div className='flex flex-wrap gap-2'>{items.map(i=><button key={i} className={cn('rounded-full px-3 py-1.5 text-sm font-semibold',i===active?'bg-navy-900 text-white':'bg-white text-navy-500 border border-navy-100')}>{i}</button>)}</div>}
